apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: core-banking-poc
type: Opaque
data:
  password: cG9zdGdyb3VwcGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: core-banking-poc
type: Opaque
data:
  username: bWluaW8=
  password: c3VwZXJzZWNyZXQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: api-tls-secret
  namespace: core-banking-poc
type: kubernetes.io/tls
data:
  tls.crt: PLACEHOLDER
  tls.key: PLACEHOLDER
