apiVersion: v1
kind: Service
metadata:
  name: funds-core-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.fundsCore.port | default 8081 }}
      targetPort: 8081
  selector:
    app: funds-core
