apiVersion: v1
kind: Service
metadata:
  name: api-edge-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.apiEdge.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.apiEdge.port | default 80 }}
      targetPort: 80
  selector:
    app: api-edge
---
