apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/temporal:latest
          ports:
            - containerPort: 8080
          env:
            - name: TEMPORAL_CLI_ADDRESS
              value: http://temporal-frontend:8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "500m"
              memory: 256Mi
